# Generated by Django 5.1.2 on 2024-10-27 06:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[app.models.validate_phone])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_pics/')),
            ],
        ),
    ]
